SEED: 7
DEBUG: False
LOG_FREQ_PRETRAINING: 1000
LOG_FREQ_DOWNSTREAM: 100
OUTPUT_BASE_DIR: '/storage/shafner/urban_extraction/networks'
SAVE_CHECKPOINTS: [10]

CHECKPOINTS:
  DOWNSTREAM: 10
  INFERENCE: 10

MODEL:
  TYPE: 'unet'
  OUT_CHANNELS: 2
  IN_CHANNELS: 10
  TOPOLOGY: [64, 128,]
  BACKBONE:
    ENABLED: False

DATALOADER:
  NUM_WORKER: 8
  SHUFFLE: True
  LABEL: 'buildings'
  LABEL_THRESH: 0.0
  SENTINEL1_BANDS: ['VV', 'VH']
  SENTINEL2_BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B6', 'B8', 'B8A', 'B11', 'B12']
  MODE: 'optical'
  AUXILIARY_INPUTS: []
  INCLUDE_UNLABELED: False


DATASETS:
  PATH: '/storage/shafner/urban_extraction/urban_dataset/'
  TRAINING: ['albuquerque', 'atlanta', 'charlston', 'columbus', 'dallas', 'denver', 'elpaso', 'houston',
             'kansascity', 'lasvegas', 'losangeles', 'miami', 'minneapolis', 'montreal', 'phoenix',
             'quebec', 'saltlakecity', 'sandiego', 'santafe', 'seattle', 'stgeorge', 'toronto',
             'tucson', 'winnipeg']
  PRETRAINING: ['houston', 'seattle', 'losangeles', 'atlanta',
             'beijing', 'dakar', 'dubai', 'jakarta', 'kairo', 'kigali', 'lagos', 'mexicocity', 'mumbai',
             'riodejanairo', 'shanghai', 'buenosaires', 'bogota', 'sanjose', 'santiagodechile', 'kapstadt', 'tripoli',
             'freetown', 'london', 'madrid', 'kinshasa', 'manila', 'moscow', 'newdehli', 'nursultan', 'perth',
             'tokio', 'stockholm', 'sidney', 'maputo', 'caracas', 'santacruzdelasierra', 'saopaulo', 'asuncion',
             'lima', 'paramaribo', 'libreville', 'djibuti', 'beirut', 'baghdad', 'athens', 'islamabad', 'hanoi',
             'bangkok', 'dhaka', 'bengaluru', 'taipeh', 'berlin', 'nanning', 'wuhan', 'daressalam', 'milano',
             'zhengzhou', 'hefei', 'xian', 'seoul', 'ibadan', 'benincity', 'abidjan', 'accra']
  VALIDATION: ['calgary', 'newyork', 'sanfrancisco', 'vancouver']
  UNLABELED: []
  TESTING: '/storage/shafner/urban_extraction/urban_dataset/sn7/'

TRAINER_PRETRAINING:
  LR: 1e-5
  BATCH_SIZE: 16
  EPOCHS: 10
  OPTIMIZER: 'adamw'
  LOSS_TYPE: 'MeanSquareErrorLoss'

TRAINER_DOWNSTREAM:
  LR: 1e-5
  BATCH_SIZE: 16
  EPOCHS: 10
  OPTIMIZER: 'adamw'
  LOSS_TYPE: 'JaccardMoreLikeLoss'
  FREEZE_ENCODER: False
  REINITIALIZE_DECODER: False

AUGMENTATION:
  IMAGE_OVERSAMPLING_TYPE: 'none' # [none, simple]
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  COLOR_SHIFT: False
  GAMMA_CORRECTION: True
  DOWNSCALE: []
  SENSOR_DROPOUT: False
  CHANNEL_DROPOUT: False