_BASE_: "base.yaml"
DEBUG: False
INFERENCE:
  CHECKPOINT: 20
  THRESHOLDS:
    TRAIN: 0.0
    VALIDATION: 0.0

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 12
  TOPOLOGY: [64, 128, 256, 512,]

DATALOADER:
  MODE: 'fusion'