_BASE_: "base.yaml"
DEBUG: True
LOG_FREQ: 1000

MODEL:
  TYPE: 'dualstreamunet'
  OUT_CHANNELS: 1
  IN_CHANNELS: 12

DATALOADER:
  MODE: 'fusion'
  INCLUDE_UNLABELED: True

TRAINER:
  BATCH_SIZE: 8

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.5
  WEIGHT_DECAY: 0.998
  APPLY_THRESHOLD: False
  CONSISTENCY_LOSS_TYPE: 'PowerJaccardLoss'