_BASE_: "base.yaml"
DEBUG: False
INFERENCE:
  CHECKPOINT: 5
  THRESHOLDS:
    TRAIN: 0.53
    VALIDATION: 0.49

MODEL:
  TYPE: 'dualstreamunet'
  IN_CHANNELS: 12

TRAINER:
  BATCH_SIZE: 8

DATALOADER:
  MODE: 'fusion'