_BASE_: "igarss_base.yaml"
DEBUG: False
SAVE_CHECKPOINTS: [20, 40]
INFERENCE:
  CHECKPOINT: 20
  THRESHOLDS:
    TRAIN: 0.00
    VALIDATION: 0.00

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 12

DATALOADER:
  MODE: 'fusion'
  INCLUDE_UNLABELED: True

TRAINER:
  BATCH_SIZE: 16
  EPOCHS: 40