_BASE_: "base.yaml"
DEBUG: False
INFERENCE:
  CHECKPOINT: 0
  THRESHOLDS:
    TRAIN: 0.00
    VALIDATION: 0.00

MODEL:
  IN_CHANNELS: 2

DATALOADER:
  MODE: 'sar'

AUGMENTATION:
  DOWNSCALE: [1, 2, 3, 4]